### ISSUE TITLE
Flutter build fails with error after new update!

### ISSUE THREAD

**Issue by nicklbaert** [Kavantix/sliver_tools#85]
The error:

```
Could not build the precompiled application for the device.
Error (Xcode): ../../../../../../.pub-cache/hosted/pub.dev/sliver_tools-0.2.10/lib/src/sliver_stack.dart:282:55: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
```

**Comment by kamranbekirovyz** [comment]
Is it closed on purpose? The issue causes my app to not run, seems like a critical issue right now, isn't it?

**Comment by Kavantix** [comment]
@kamranbekirovyz  Looking at the error he posted he was using 0.2.10 but this is fixed in >=0.2.11

**Comment by kamranbekirovyz** [comment]
I see. `infinite_scroll_pagination` package still depends on `sliver_tools 0.2.9`, I'll do a dependency override.

When I checked pub.dev, I saw that the last release is 36 days ago, which made me think this is not fixed. Whereas it has been fixed in version 0.2.11. #BackToTheFuture

<img width="856" alt="Screenshot 2023-08-22 at 18 30 05" src="https://github.com/Kavantix/sliver_tools/assets/59581562/14aed4eb-cf3e-43ba-8dc7-c22a74f62747">

**Comment by Kavantix** [comment]
infinite_scroll_pagination is up to date, you are probably using an old version of that too I guess

> When I checked pub.dev, I saw that the last release is 36 days ago, which made me think this is not fixed. Whereas it has been fixed in version 0.2.11. #BackToTheFuture

Yeah people were already testing flutter 3.13 on the beta/master channels ;)
